// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kthkrpqnfixwoelslbml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0aGtycHFuZml4d29lbHNsYm1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODM2OTcsImV4cCI6MjA1OTI1OTY5N30.ojYy6D15a_SqijQRcgDv5kVppC9Uyz9UF0RjzCbvJPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);